<%

require "run_loop"

if RunLoop::Environment.ci?
  formatter = "pretty"
else
  formatter = "Slowhandcuke::Formatter"
end

%>

formatter: -f <%= formatter %>
default: CBXWS=../CBXDriver.xcworkspace -p formatter
verbose: DEBUG=1

